//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dexter.Analyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dexter.Analyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; contains lowercase letters.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Type should have a doxygen comment.
        /// </summary>
        internal static string NoCommentAnalyzerDescription {
            get {
                return ResourceManager.GetString("NoCommentAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Type &apos;{0}&apos; has no doxygen comment.
        /// </summary>
        internal static string NoCommentAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NoCommentAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API type has no doxygen comment.
        /// </summary>
        internal static string NoCommentAnalyzerTitle {
            get {
                return ResourceManager.GetString("NoCommentAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml tag shoul have the end tag.
        /// </summary>
        internal static string NoEndTagAnalyzerDescription {
            get {
                return ResourceManager.GetString("NoEndTagAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml tag &apos;{0}&apos; has no end tag.
        /// </summary>
        internal static string NoEndTagAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NoEndTagAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml tag has no end tag.
        /// </summary>
        internal static string NoEndTagAnalyzerTitle {
            get {
                return ResourceManager.GetString("NoEndTagAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File should have a doxygen comment.
        /// </summary>
        internal static string NoFileCommentAnalyzerDescription {
            get {
                return ResourceManager.GetString("NoFileCommentAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; has no doxygen comment.
        /// </summary>
        internal static string NoFileCommentAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NoFileCommentAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has no doxygen comment.
        /// </summary>
        internal static string NoFileCommentAnalyzerTitle {
            get {
                return ResourceManager.GetString("NoFileCommentAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml tag shoul have a description.
        /// </summary>
        internal static string NoXmlTextAnalyzerDescription {
            get {
                return ResourceManager.GetString("NoXmlTextAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml tag &apos;{0}&apos; has no description.
        /// </summary>
        internal static string NoXmlTextAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NoXmlTextAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml tag has no description.
        /// </summary>
        internal static string NoXmlTextAnalyzerTitle {
            get {
                return ResourceManager.GetString("NoXmlTextAnalyzerTitle", resourceCulture);
            }
        }
    }
}
