//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dexter.Analyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dexter.Analyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Type should have a code comment.
        /// </summary>
        internal static string NoCodeRuleDescription {
            get {
                return ResourceManager.GetString("NoCodeRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Type &apos;{0}&apos; has no code comment.
        /// </summary>
        internal static string NoCodeRuleMessageFormat {
            get {
                return ResourceManager.GetString("NoCodeRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Type has no code comment.
        /// </summary>
        internal static string NoCodeRuleTitle {
            get {
                return ResourceManager.GetString("NoCodeRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File should have a doxygen comment.
        /// </summary>
        internal static string NoCommentFileRuleDescription {
            get {
                return ResourceManager.GetString("NoCommentFileRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; has no doxygen comment.
        /// </summary>
        internal static string NoCommentFileRuleMessageFormat {
            get {
                return ResourceManager.GetString("NoCommentFileRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has no doxygen comment.
        /// </summary>
        internal static string NoCommentFileRuleTitle {
            get {
                return ResourceManager.GetString("NoCommentFileRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Type should have a doxygen comment.
        /// </summary>
        internal static string NoCommentRuleDescription {
            get {
                return ResourceManager.GetString("NoCommentRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Type &apos;{0}&apos; has no doxygen comment.
        /// </summary>
        internal static string NoCommentRuleMessageFormat {
            get {
                return ResourceManager.GetString("NoCommentRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API type has no doxygen comment.
        /// </summary>
        internal static string NoCommentRuleTitle {
            get {
                return ResourceManager.GetString("NoCommentRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml tag shoul have the end tag.
        /// </summary>
        internal static string NoEndTagRuleDescription {
            get {
                return ResourceManager.GetString("NoEndTagRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml tag &apos;{0}&apos; has no end tag.
        /// </summary>
        internal static string NoEndTagRuleMessageFormat {
            get {
                return ResourceManager.GetString("NoEndTagRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml tag has no end tag.
        /// </summary>
        internal static string NoEndTagRuleTitle {
            get {
                return ResourceManager.GetString("NoEndTagRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception throwed in API shoud have a exception comment.
        /// </summary>
        internal static string NoExceptionRuleDescription {
            get {
                return ResourceManager.GetString("NoExceptionRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; throwed in API has no exception comment.
        /// </summary>
        internal static string NoExceptionRuleMessageFormat {
            get {
                return ResourceManager.GetString("NoExceptionRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception throwed in API has no exception comment.
        /// </summary>
        internal static string NoExceptionRuleTitle {
            get {
                return ResourceManager.GetString("NoExceptionRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Parameter shoud have a param comment.
        /// </summary>
        internal static string NoParamRuleDescription {
            get {
                return ResourceManager.GetString("NoParamRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Parameter &apos;{0}&apos; has no param comment.
        /// </summary>
        internal static string NoParamRuleMessageFormat {
            get {
                return ResourceManager.GetString("NoParamRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Parameter has no param comment.
        /// </summary>
        internal static string NoParamRuleTitle {
            get {
                return ResourceManager.GetString("NoParamRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with a return type should have a returns comment.
        /// </summary>
        internal static string NoReturnsRuleDescription {
            get {
                return ResourceManager.GetString("NoReturnsRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; has no returns comment.
        /// </summary>
        internal static string NoReturnsRuleMessageFormat {
            get {
                return ResourceManager.GetString("NoReturnsRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with a return type has no returns comment.
        /// </summary>
        internal static string NoReturnsRuleTitle {
            get {
                return ResourceManager.GetString("NoReturnsRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Type should have a summary comment.
        /// </summary>
        internal static string NoSummaryRuleDescription {
            get {
                return ResourceManager.GetString("NoSummaryRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Type &apos;{0}&apos; has no summary comment.
        /// </summary>
        internal static string NoSummaryRuleMessageFormat {
            get {
                return ResourceManager.GetString("NoSummaryRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Type has no summary comment.
        /// </summary>
        internal static string NoSummaryRuleTitle {
            get {
                return ResourceManager.GetString("NoSummaryRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml tag shoul have a description.
        /// </summary>
        internal static string NoXmlTextRuleDescription {
            get {
                return ResourceManager.GetString("NoXmlTextRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml tag &apos;{0}&apos; has no description.
        /// </summary>
        internal static string NoXmlTextRuleMessageFormat {
            get {
                return ResourceManager.GetString("NoXmlTextRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml tag has no description.
        /// </summary>
        internal static string NoXmlTextRulerTitle {
            get {
                return ResourceManager.GetString("NoXmlTextRulerTitle", resourceCulture);
            }
        }
    }
}
