Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "dexter-server"
  config.vm.network "forwarded_port", guest: 4982, host: 4982
  config.vm.provision "shell", :path => "provision/bootstrap.sh"
  config.vm.provision "shell", :path => "provision/install_mysql.sh"
  config.vm.provision "shell", :path => "provision/create_dexter_db.sh"
  config.vm.provision "shell", :path => "provision/install_nodejs.sh"
  config.vm.post_up_message = "Provisioning Completed successfully! Please access to http://localhost:4982/defect"
end
